-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."D_Customer"
(
    "CUS_ID" integer NOT NULL,
    "CUS_BKey" text NOT NULL,
    "CUS_Gender" text NOT NULL,
    "CUS_Partner" text NOT NULL,
    "CUS_Dependents" text NOT NULL,
    "START_DATE" timestamp with time zone,
    "END_DATE" timestamp with time zone,
    CONSTRAINT "CUS_PK" PRIMARY KEY ("CUS_ID")
);

CREATE TABLE IF NOT EXISTS public."D_Product"
(
    "PRD_ID" integer NOT NULL,
    "PRD_BKEY" text NOT NULL,
    "PRD_LINE" text NOT NULL,
    "PRD_NAME" text NOT NULL,
    "START_DATE" timestamp with time zone NOT NULL,
    "END_DATE" timestamp with time zone NOT NULL,
    "PRD_LONG_NAME" text NOT NULL,
    CONSTRAINT "PRD_PK" PRIMARY KEY ("PRD_ID")
);

COMMENT ON TABLE public."D_Product"
    IS 'Product offering to customers ';

CREATE TABLE IF NOT EXISTS public."D_Contract"
(
    "CON_ID" integer NOT NULL,
    "CON_BKEY" text NOT NULL,
    "CON_NAME" text NOT NULL,
    "START_DATE" timestamp with time zone NOT NULL,
    "END_DATE" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CON" PRIMARY KEY ("CON_ID")
);

CREATE TABLE IF NOT EXISTS public."F_Measures"
(
    "CUS_ID" integer NOT NULL,
    "CON_ID" integer NOT NULL,
    "MS_Charge_Month" double precision,
    "PM_ID" integer NOT NULL,
    "DATE_ID" integer NOT NULL,
    "BM_ID" integer NOT NULL,
    "MS_Charge_Total" double precision,
    "MS_Churn" integer,
    "MS_Tenure" integer
);

COMMENT ON TABLE public."F_Measures"
    IS 'Charge incurred by customer for financial period
Tenure of contract 
Churn measure
';

CREATE TABLE IF NOT EXISTS public."D_Payment_Method"
(
    "PM_ID" integer NOT NULL,
    "PM_BKEY" text NOT NULL,
    "PM_NAME" text NOT NULL,
    "START_DATE" timestamp with time zone NOT NULL,
    "END_DATE" timestamp with time zone NOT NULL,
    CONSTRAINT "PM_PK" PRIMARY KEY ("PM_ID")
);

CREATE TABLE IF NOT EXISTS public."D_Date"
(
    "DATE_ID" integer NOT NULL,
    "CAL_BKEY" text NOT NULL,
    "CAL_YEAR" integer NOT NULL,
    "CAL_MONTH" integer NOT NULL,
    "CAL_MONTH_START" date NOT NULL,
    "CAL_MONTH_END" date NOT NULL,
    CONSTRAINT "DATE_PK" PRIMARY KEY ("DATE_ID")
);

CREATE TABLE IF NOT EXISTS public."D_Billing_Method"
(
    "BM_ID" integer NOT NULL,
    "BM_BKEY" text NOT NULL,
    "BM_NAME" text NOT NULL,
    "START_DATE" timestamp with time zone NOT NULL,
    "END_DATE" timestamp with time zone NOT NULL,
    CONSTRAINT "BM_PK" PRIMARY KEY ("BM_ID")
);

COMMENT ON TABLE public."D_Billing_Method"
    IS 'How customers are billed';

CREATE TABLE IF NOT EXISTS public."F_Subscriptions"
(
    "CUS_ID" integer NOT NULL,
    "CON_ID" integer NOT NULL,
    "PM_ID" integer NOT NULL,
    "DATE_ID" integer NOT NULL,
    "PRD_ID" integer NOT NULL,
    "BM_ID" integer NOT NULL,
    "SUB" integer
);

COMMENT ON TABLE public."F_Subscriptions"
    IS 'Customer product subscriptions for period ';

CREATE TABLE IF NOT EXISTS public."F_Charges"
(
    "CUS_ID" integer NOT NULL,
    "CON_ID" integer NOT NULL,
    "CHG_Charge" double precision,
    "PM_ID" integer NOT NULL,
    "DATE_ID" integer NOT NULL,
    "BM_ID" integer NOT NULL
);

COMMENT ON TABLE public."F_Charges"
    IS 'Charges incurred by customer for financial period
Derived purely for demo purpose
';

ALTER TABLE IF EXISTS public."F_Measures"
    ADD CONSTRAINT "FK_CUS" FOREIGN KEY ("CUS_ID")
    REFERENCES public."D_Customer" ("CUS_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Measures"
    ADD CONSTRAINT "FK_DATE" FOREIGN KEY ("DATE_ID")
    REFERENCES public."D_Date" ("DATE_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Measures"
    ADD CONSTRAINT "FK_CON" FOREIGN KEY ("CON_ID")
    REFERENCES public."D_Contract" ("CON_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Measures"
    ADD CONSTRAINT "FK_PM" FOREIGN KEY ("PM_ID")
    REFERENCES public."D_Payment_Method" ("PM_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Measures"
    ADD CONSTRAINT "BM_ID" FOREIGN KEY ("BM_ID")
    REFERENCES public."D_Billing_Method" ("BM_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Subscriptions"
    ADD CONSTRAINT "CUS_ID" FOREIGN KEY ("CUS_ID")
    REFERENCES public."D_Customer" ("CUS_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Subscriptions"
    ADD CONSTRAINT "CON_ID" FOREIGN KEY ("CON_ID")
    REFERENCES public."D_Contract" ("CON_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Subscriptions"
    ADD CONSTRAINT "PM_ID" FOREIGN KEY ("PM_ID")
    REFERENCES public."D_Payment_Method" ("PM_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Subscriptions"
    ADD CONSTRAINT "DATE_ID" FOREIGN KEY ("DATE_ID")
    REFERENCES public."D_Date" ("DATE_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Subscriptions"
    ADD CONSTRAINT "PRD_ID" FOREIGN KEY ("PRD_ID")
    REFERENCES public."D_Product" ("PRD_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Subscriptions"
    ADD CONSTRAINT "BM_ID" FOREIGN KEY ("BM_ID")
    REFERENCES public."D_Billing_Method" ("BM_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Charges"
    ADD CONSTRAINT "CUS_ID" FOREIGN KEY ("CUS_ID")
    REFERENCES public."D_Customer" ("CUS_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Charges"
    ADD CONSTRAINT "CON_ID" FOREIGN KEY ("CON_ID")
    REFERENCES public."D_Contract" ("CON_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Charges"
    ADD CONSTRAINT "PM_ID" FOREIGN KEY ("PM_ID")
    REFERENCES public."D_Payment_Method" ("PM_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Charges"
    ADD CONSTRAINT "DATE_ID" FOREIGN KEY ("DATE_ID")
    REFERENCES public."D_Date" ("DATE_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."F_Charges"
    ADD CONSTRAINT "BM_ID" FOREIGN KEY ("BM_ID")
    REFERENCES public."D_Billing_Method" ("BM_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;